syntax on

filetype plugin indent on
filetype plugin on

if $COLORTERM == 'gnome-terminal'
  set term=gnome-256color
  colorscheme peachpuff
else
  colorscheme peachpuff
endif

" NERDTree
let NERDTreeShowHidden=1
let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp', '\.git', 'node_modules', 'venv', '\.pyc']

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" split navigations
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-H> <C-W>h

" kiteco
let g:kite_tab_complete=1
nmap <silent> <buffer> gK <Plug>(kite-docs)

" Enable folding
set foldmethod=indent
set foldlevel=99

" set showmode
set noshowmode
set laststatus=2

" Make Vim more useful
set nowrap        " don't wrap lines
set backspace=indent,eol,start
                  " allow backspacing over everything in insert mode
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set smarttab      " insert tabs on the start of a line according to
                  "    shiftwidth, not tabstop
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type

set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab

set scrolloff=3

set wildmenu      " Enhance command-line completion
set showcmd       " Show the (partial) command as it’s being typed
